Tekno-Point/internal-aem-eds-poc-en

- .github/pull_request_template.md
- README.md
- fstab.yaml
- paths.json
Test URLs:
- After: https://main-impl--internal-aem-eds-poc-en--Tekno-Point.aem.live/
> config setup for the repo with EDS

- paths.json
Test URLs:
- After: https://dev--internal-aem-eds-poc-en--Tekno-Point.aem.live/
> change in pathsjson file

- paths.json
Test URLs:
- After: https://dev--internal-aem-eds-poc-en--Tekno-Point.aem.live/
>  form path added

- paths.json
> test added in mapping

- paths.json
> form path modified

- blocks/header/header.css
>  z index added

- paths.json
>  image url sheet path added

- paths.json
>  city model paths added

- blocks/header/header.js
> header overflow property set

- paths.json
> path json form added

- paths.json
> paths updated

- paths.json
> add form json in path.json

- paths.json
> Headers JSON added

- blocks/footer/footer.js
- blocks/form/form.css
- blocks/fragment/fragment.js
- blocks/header/header.js
- package.json
- scripts/aem.js
- scripts/scripts.js
>  Auto Fragment Js Added

- paths.json
> added in path.json for tataaia banner form

- blocks/form/booking-form.js
- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
- component-definition.json
- component-filters.json
- component-models.json
Test URLs:
- Before: https://srilankan-airlines--internal-aem-eds-poc-en--Tekno-Point.aem.live/
- After: https://srilanka-carousel--internal-aem-eds-poc-en--Tekno-Point.aem.live/
> Srilanka carousel

- paths.json
> added new path json

- blocks/content-fragment/content-fragment.css
Test URLs:
- After: https://trending-options--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines/
> Trending options

- paths.json
> path added

- blocks/header/header.css
- component-definition.json
- component-filters.json
- component-models.json
Test URLs:
- Before: https://icici-lombard--internal-aem-eds-poc-en--Tekno-Point.aem.live/
- After: https://icicil-footer--internal-aem-eds-poc-en--Tekno-Point.aem.live/
> Icicil footer

- blocks/form/form.css
- blocks/header/header.css
- blocks/header/header.js
- blocks/header/loginform.css
> header pop's

- blocks/table/table.css
- blocks/table/table.js
- blocks/table/temp__table.json
- component-definition.json
- component-filters.json
- component-models.json
> Icicil table

- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
Test URLs:
- After: https://srilanka-carousel--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines/
> price added in card

- blocks/faq-accordion/faq-accordion.js
- blocks/overview-rte/overview-rte.js
- blocks/pl-blogs/pl-blogs.js
- blocks/rte-block/rte-block.css
- blocks/rte-block/rte-block.js
- blocks/secondary-navbar/secondary-navbar.js
- blocks/swipper-card/swipper-card.css
- styles/styles.css
Test URLs:
- Before: https://idfcbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
- After: https://idfc-dev--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
> style fixes

- blocks/cf-fragment/cf-fragment.css
- blocks/cf-fragment/cf-fragment.js
- blocks/columns/columns.css
- blocks/columns/columns.js
- styles/styles.css
Test URLs:
- Before: https://idfcbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
- After: https://idfc-banner--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
> form changes

- blocks/cf-fragment/cf-fragment.css
- blocks/columns/columns.css
- styles/styles.css
Test URLs:
- Before: https://idfcbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
- After: https://idfc-banner--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
> banner fixes

- blocks/tabs/tabs.js
Test URLs:
- Before: https://srilankan-airlines--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines
- After: https://srilanka-carousel--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines
> token added

- blocks/header/mob-header.css
Test URLs:
- Before: https://idfcbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
- After: https://header-idfc-fix--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
> nav-list block css

- blocks/header/mob-header.css
Test URLs:
- Before: https://main--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank
- After: https://header-idfc-fix--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank
> icon addition for nav subtitlt

- blocks/cf-fragment/cf-fragment.css
- blocks/columns/columns.css
- styles/styles.css
Test URLs:
- Before: https://idfcbank-optimization--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
- After: https://idfc-dev--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank/
> issues fixes

- component-models.json
Test URLs:
- After: https://idfcb-header-footer--internal-aem-eds-poc-en--Tekno-Point.aem.live/
> section class added display none

- blocks/header/header.css
Test URLs:
- Before: https://main--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank
- After: https://idfcb-header-footer--internal-aem-eds-poc-en--Tekno-Point.aem.live/idfcfirstbank
> display none headers footer in desktop

- blocks/carousel/banner-carousel.css
Test URLs:
- After: https://srilankan-cta--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines/
>  cta page added

- blocks/content-fragment/content-fragment.js
Test URLs:
- After: https://srilanka-carousel--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines/
> query parameter added

- blocks/carousel/deals-carousel.css
- blocks/carousel/services-carousel.css
- blocks/header/header.css
- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
- styles/styles.css
Test URLs:
- After: https://srilanka-carousel--internal-aem-eds-poc-en--Tekno-Point.aem.live/srilankan-airlines/
> loader added

- component-definition.json
- component-models.json
Test URLs:
- Before: https://icici-lombard--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard
- After: https://icicil-forms--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard
> basic-form

- blocks/form/add-travellers.js
- blocks/form/form-fields.js
- blocks/form/form.css
- blocks/form/form.js
- blocks/form/single-trip.js
- blocks/hero/single-trip.css
- scripts/scripts.js
> Form logic 17

- blocks/form/form.js
- blocks/form/formToggler.js
Test URLs:
Before: https://icici-lombard--internal-aem-eds-poc-en--tekno-point.aem.live/icicilombard
After: https://icicil-forms--internal-aem-eds-poc-en--tekno-point.aem.live/icicilombard
> Icicil forms

- blocks/form/form.css
- blocks/hero/hero.css
- blocks/hero/single-trip.css
> Form mobile

- blocks/header/header.css
- component-models.json
- scripts/delayed.js
Test URLs:
- Before: https://icici-lombard--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard
- After: https://icicil-forms--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard
> ria live chat styling

- blocks/form/form.css
- blocks/form/form.js
Test URLs:
- Before: https://icici-lombard--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard/
- After: https://icicil-forms--internal-aem-eds-poc-en--Tekno-Point.aem.live/icicilombard/
> on extend policy button click toggle extend policy form

- blocks/about-us/_about-us.json
- blocks/about-us/about-us.css
- blocks/about-us/about-us.js
- component-definition.json
- component-filters.json
- component-models.json
- scripts/delayed.js
- styles/styles.css
> Esafbank aboutus

- paths.json
> icici-lombard test forms paths.json

- blocks/footer/footer.css
- component-models.json
- styles/styles.css
Test URLs:
- Before: https://esafbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/esafbank/
- After: https://esafbank-footer--internal-aem-eds-poc-en--Tekno-Point.aem.live/esafbank/
> Esafbank footer

- blocks/content-fragment/content-fragment.css
- blocks/content-fragment/content-fragment.js
- component-definition.json
- component-filters.json
- component-models.json
- scripts/delayed.js
Test URLs:
- Before: https://esafbank--internal-aem-eds-poc-en--Tekno-Point.aem.live/esafbank/
- After: https://esafbank-body--internal-aem-eds-poc-en--Tekno-Point.aem.live/esafbank/
> Esafbank body

- paths.json
Test URLs:
- Before: https://main--internal-aem-eds-poc-en--Tekno-Point.aem.live/poonawallafincorp/home
- After: https://poonawala-lib--internal-aem-eds-poc-en--Tekno-Point.aem.live/poonawallafincorp/home
> libraray added
